version: '3.9'
services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ./nuxtApp:/usr/src/app
    ports:
    - "8070:8080"
